version: 0.2

phases:
  install:
    commands:
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - yum install -y awscli tar wget gzip make jq gettext bash-completion moreutils
      - curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      - mv -v /tmp/eksctl /usr/local/bin
      - eksctl completion bash >> ~/.bash_completion
  pre_build:
    commands:
      - if [`aws iam get-policy --policy-arn arn:aws:iam::485323199507:policy/ALBIngressControllerIAMPolicy| wc -l` -eq 0 ]; then echo "creating"; fi
      - export ALB_INGRESS_POLICY_ARN=arn:aws:iam::485323199507:policy/ALBIngressControllerIAMPolicy
      - eksctl version
      - echo Entered the pre_build phase...
      - echo Logging in to Amazon EKS...
      - kubectl version --short --client
      - | 
        sed -i 's!config_cluster_name!'$CLUSTER_NAME'!; 
        s!config_aws_region!'$AWS_REGION'!; 
        s!config_tag_environment!'$ENV'!; 
        s!config_tag_owner!'$OWNER'!; 
        s!config_tag_team!'$TEAM'!; 
        s!config_alb_policy_arn!'$ALB_INGRESS_POLICY_ARN'!; 
        s!config-sub_priv_a!'$PRIVATE_SUB_A'!; 
        s!config-sub_priv_b!'$PRIVATE_SUB_B'!; 
        s!config-sub_pub_a!'$PUBLIC_SUB_A'!; 
        s!config-sub_pub_b!'$PUBLIC_SUB_B'!; 
        s!config_ng_cap!'$NODE_GROUP_CAP'!; 
        s!config_kms_arn!'$KMS_ARN'!' kubernetes/cluster-config.yaml
      - cat kubernetes/cluster-config.yaml
  build:
    commands:
      - eksctl create cluster -f kubernetes/cluster-config.yaml
      - kubectl get nodes
      - | 
        sed -i 's!def-cluster-name!'$CLUSTER_NAME'!;
        s!def-aws-region!'$AWS_REGION'!; 
        s!def-vpc-id!'$VPC'!' kubernetes/ingress/alb-ingress-rbac.yaml
      - cat kubernetes/ingress/alb-ingress-rbac.yaml
      - kubectl apply -f kubernetes/ingress/alb-ingress-rbac.yaml
      - kubectl get all -n kube-system

  post_build:
    commands:
      - echo Build completed on `date`
