version: 0.2

phases:
  install:
    commands:
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - yum install -y awscli tar wget
      - curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      - sudo mv -v /tmp/eksctl /usr/local/bin
      - eksctl completion bash >> ~/.bash_completion
  pre_build:
    commands:
      - eksctl version
      - echo Entered the pre_build phase...
      - echo Logging in to Amazon EKS...
      - kubectl version --short --client
      - ls -la
      - pwd
  build:
    commands:
      - make
      - kubectl get nodes
  post_build:
    commands:
      - echo Build completed on `date`
